from django.contrib import admin
from .models import *

admin.site.register(Impactos)
admin.site.register(TipoCafetos)
admin.site.register(TipoVariedad)
admin.site.register(TipoSombra)
admin.site.register(Fertilizacion)
admin.site.register(TipoAplicacionFungicida)
admin.site.register(Combatir)
admin.site.register(Productos)
admin.site.register(AdelanteTipoCafetos)
admin.site.register(AdelanteTipoVariedad)
admin.site.register(AdelanteTipoSombra)
admin.site.register(AdelanteFertilizacion)
admin.site.register(AdelanteTipoAplicacionFungicida)
admin.site.register(Igual)
admin.site.register(Mas)
admin.site.register(Menos)
admin.site.register(Variedades)
admin.site.register(TipoCapacitaciones)
admin.site.register(Capacitor)
admin.site.register(Metodologia)
admin.site.register(TemasSociales)
admin.site.register(Plantio)
admin.site.register(TipoFertilizacion)
admin.site.register(TipoFungicida)